### PR TITLE
Fix empty directory cleanup when deleting a deeply nested key

### LINKED ISSUE #375: Removing last nested object leaves directories behind
It looks like this was raised in #39 and partially fixed in #103.

For example, if a bucket only contains one object with key `dir1/dir2/dir3/file`, calling `deleteObject` leaves behind the directories `dir1/dir2`.  It looks like `utils.removeEmptyDirectories` is recursing top-down through the directories, so it only deems `dir3` to be empty.

Full example:

_index.js_
```js
'use strict';
const {S3} = require('aws-sdk');
const s3 = new S3({ endpoint: 'http://localhost:4568', s3ForcePathStyle: true });

(async () => {
  await s3.putObject({
    Bucket: 'my-bucket',
    Key: 'dir1/dir2/dir3/file',
    Body: 'file 1'
  }).promise();

  await s3.deleteObject({
    Bucket: 'my-bucket',
    Key: 'dir1/dir2/dir3/file'
  }).promise();

  await s3.deleteBucket({ Bucket: 'my-bucket' }).promise();
})();

```
```shell
> mkdir my-bucket
> s3rver -d $PWD &
> node .
(node:11098) UnhandledPromiseRejectionWarning: BucketNotEmpty: The bucket your tried to delete is not empty
> ls -R my-bucket
my-bucket:
dir1

my-bucket/dir1:
dir2

my-bucket/dir1/dir2:
```

### PR DESCRIPTION
**Pull request by kherock**
Resolves #375. The old implementation didn't check if the directory was empty after running the function on its children.

### CODE REVIEW

File: test/test.js [hunk 1]
```diff
@@ -1643,20 +1643,18 @@ describe("Data directory cleanup", function() {
...
       yield s3Client.deleteBucket({ Bucket: bucket }).promise();
-    } catch (err) {
-      throw err;
     } finally {
       yield thunkToPromise(done => server.close(done));
     }
   });
 
-  it("Can put an object in a bucket that is empty after some key that does not include a directory has been deleted", function*() {
+  it("Can put an object in a bucket after all objects are deleted", function*() {
```
Comment (leontastic) [inline test/test.js]: Nice that is a _way better_ test description
